import fs from "fs"
import { EntryFiles } from "../typings"
import {format} from "./"
export async function writeManifest(path: string, entries: EntryFiles, author: string): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    fs.promises.writeFile(`${path}/fxmanifest.lua`,
      `
      fx_version "cerulean"
      games { 'rdr3', 'gta5' }
      description 'This manifest was generated by fxmanifestmaker by LedAndris'
      version '1.0.0'
      author '${author}'

      ui_page ${entries.UIP[0].replace(",", "")}
      client_scripts ${format(entries.CL).join("")}

      server_scripts ${format(entries.SV).join("")}

      shared_scripts ${format(entries.SH).join("")}

      files ${format(entries.FILE).join("")}
      ${"\n"}
      ${entries.DATA_FILES.join("\n")}

      `)
      .then(() => {
      resolve()
    })
  })

}