
      fx_version "cerulean"
      games { 'rdr3', 'gta5' }
      description 'This manifest was generated by fxmanifestmaker by LedAndris'
      version '1.0.0'
      author 'desktop'

      
      client_scripts {
        {}
}

      server_scripts {
          {
'sv.lua',}
}

      shared_scripts {
            {}
}

      files {
              {
'test2/bloodfx.dat','test2/shit.xml',}
}
      

      data_file 'POPSCHED_FILE' 'test2/bloodfx.dat'
data_file 'OVERLAY_INFO_FILE' 'test2/shit.xml'

      